apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-development/*
build:
  local:
    push: false
  artifacts:
    - image: schachte1/client
      context: client
      docker:
        dockerfile: devDockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: schachte1/posts
      context: server/Posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: schachte1/comments
      context: server/Comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .