apiVersion: apps/v1
kind: Deployment
metadata:
    name: posts-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: posts
    template:
        metadata:
            labels:
                app: posts
        spec:
            containers:
                - name: posts
                  image: schachte1/posts
                  env:
                    - name: dbuser
                      valueFrom: 
                        secretKeyRef:
                            name: databaseuser
                            key: undb
                    - name: dbpassword
                      valueFrom: 
                        secretKeyRef:
                            name: pwdb
                            key: pwdb
                    - name: database
                      value: "personalblog"
---
apiVersion: v1
kind: Service
metadata:
    name: posts-srv
spec:
    selector:
        app: posts
    type: ClusterIP
    ports:
        - name: posts
          protocol: TCP
          port: 80
          targetPort: 4000
