name: deploy-posts

on: 
  push:
    branches: master
    paths:
      - 'server/Posts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server/Posts && docker build -t schachte1/posts .
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      - run: docker push schachte1/posts
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ryan-schachte-personal
      - run: kubectl rollout restart deployment posts-depl
