name: deploy-manifests
on: 
  push:
    branches: master
    paths:
      - 'infra/k8s/_*/**'
      - 'infra/k8s/k8s-production/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ryan-schachte-personal
      - run: kubectl apply -f infra/k8s --recursive && kubectl apply -f infra/k8s-production --recursive
